[package]
name = "gltch"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
iced = {git = "https://github.com/iced-rs/iced", branch = "master", commit = "92888a3639bdfb8e4ebea91e752d25825d8d8886", features = ["image"]}
image = "0.25.8"
log = "0.4.28"
rfd = "0.15.4"
smol = "2.0.2"
wgpu = "27.0.1"


[lints.rust]
missing_docs = "forbid"